# Site\
name: "Flora Media Blog"
description: "Il racconto delle nostre avventure"
meta_description: "Il racconto delle nostre avventure"
logo: "assets/images/logo.jpg"
favicon: "assets/images/logo2.png"
baseurl: ""

# Authors
authors:
  tommaso:
    name: Tommaso
    display_name: Tommaso
    gravatar: avatar.png
    description: "Il secchione della classe, appassionato di nuoto e influencer su instagram"
  gaia:
    name: Gaia
    display_name: Gaia
    gravatar: gaia2019.jpg
    description: "Appassionata d'equitazione" 
  benedetta:
    name: Benedetta
    display_name: Benedetta
    gravatar: benedetta2019.png
    description: "Appassionata di pattinaggio"
  niccolo:
    name: Niccolo
    display_name: Niccolò
    gravatar: avatar.png
    description: "Giocatore di calcio nella squadra giovanile della Juventus"
  classe_3:
    name: classe_3
    display_name: "Classe 3 A.S. 2018-2019"
    gravatar: classe_3_2018.jpg
    description: "Classe 3 A.S. 2018-2019"  
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
