# Site
name: "Flora Media Blog"
description: "Il racconto delle nostre avventure"
meta_description: "Il racconto delle nostre avventure"
logo: "assets/images/logo.jpg"
favicon: "assets/images/logo2.png"
baseurl: ""

# Authors
authors:
  tommaso:
    name: Tommaso
    display_name: Tommaso
    gravatar: avatar.png
    description: "Il secchione della classe, appassionato di nuoto e influencer su instagram"
  gaia:
    name: Gaia
    display_name: Gaia
    gravatar: gaia2019.jpg
    description: "Appassionata d'equitazione"  
  
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
